# PURE VAMA TRADING ALGO (Price Only)
# Uses price_data.json generated by price_generator.py 
# No volume, no momentum — ONLY VAMA for trend entry & exit
# Reads price only (new exchange file) :contentReference[oaicite:3]{index=3}

import json
import time
import numpy as np
from collections import deque
from datetime import datetime

# ========================
# CONFIG
# ========================
PRICE_FILE = "price_data.json"

LOOKBACK = 20                  # 20-price volatility window
ALPHA_MIN = 0.02               # slowest smoothing
ALPHA_MAX = 0.20               # fastest smoothing
SLEEP = 2                      # sync with generator
QTY = 100                      # fixed position size
SUMMARY_INTERVAL = 60          # print summary every 60 secs

START_CAPITAL = 100000
MAX_DRAWDOWN = 0.05            # 5%

# ========================
# STATE
# ========================
prices = deque(maxlen=LOOKBACK)
vama_prev = None

position = 0                   # 0 = FLAT, 1 = LONG, -1 = SHORT
entry_price = 0
entry_time = ""
realised_pnl = 0
capital = START_CAPITAL

last_summary = time.time()


# ========================
# READ PRICE
# ========================
def read_price():
    try:
        with open(PRICE_FILE, "r") as f:
            d = json.load(f)
        return float(d["price"])
    except:
        return None


# ========================
# VAMA CALC
# ========================
def compute_alpha(prices_arr):
    # Volatility = StdDev of last 20 prices
    vol = np.std(prices_arr)

    # Average Volatility = same StdDev (smooth version optional)
    avg_vol = vol

    if avg_vol == 0:
        return ALPHA_MIN  # avoid division by zero

    raw_alpha = vol / avg_vol  # normally =1, but adaptive in real data

    # Clamp alpha
    alpha = max(ALPHA_MIN, min(ALPHA_MAX, raw_alpha))
    return alpha


def compute_vama(price, vama_prev, alpha):
    if vama_prev is None:
        return price  # first VAMA equals first price
    return alpha * price + (1 - alpha) * vama_prev


# ========================
# PRINT POSITION
# ========================
def print_status(price):
    if position == 1:
        unreal = (price - entry_price) * QTY
        print(f"   ▶ LONG @ {entry_price} | Unreal: {unreal:.2f} | Real: {realised_pnl:.2f}")
    elif position == -1:
        unreal = (entry_price - price) * QTY
        print(f"   ▶ SHORT @ {entry_price} | Unreal: {unreal:.2f} | Real: {realised_pnl:.2f}")
    else:
        print(f"   ▶ FLAT | Realised: {realised_pnl:.2f}")


# ========================
# MAIN LOOP
# ========================
print("\n🚀 PURE VAMA TREND ALGO STARTED (Price Only)\n")

while True:
    price = read_price()
    if price is None:
        print("Waiting for price...")
        time.sleep(SLEEP)
        continue

    prices.append(price)
    now = datetime.now().strftime("%H:%M:%S")

    if len(prices) < LOOKBACK:
        print(f"[Warm-up] {len(prices)}/{LOOKBACK} | Price={price}")
        time.sleep(SLEEP)
        continue

    # ------------------------
    # VAMA CALCULATION
    # ------------------------
    arr = np.array(prices)
    alpha = compute_alpha(arr)
    vama = compute_vama(price, vama_prev, alpha)
    vama_prev = vama

    print(f"[{now}] Price={price:.2f}  VAMA={vama:.2f}  α={alpha:.4f}")
    print_status(price)

    # ------------------------
    # ENTRY LOGIC (PURE VAMA)
    # ------------------------
    if position == 0:
        if price > vama:
            position = 1
            entry_price = price
            entry_time = now
            print(f"🟢 LONG ENTERED @ {price:.2f} | WHY: Price > VAMA")
        elif price < vama:
            position = -1
            entry_price = price
            entry_time = now
            print(f"🔴 SHORT ENTERED @ {price:.2f} | WHY: Price < VAMA")

    # ------------------------
    # EXIT LOGIC (PURE VAMA)
    # ------------------------
    else:
        if position == 1:  # LONG
            if price <= vama:
                pnl = (price - entry_price) * QTY
                realised_pnl += pnl
                capital += pnl
                print(f"🔵 LONG EXIT @ {price:.2f} | REASON: Price <= VAMA | PnL={pnl:.2f}")
                position = 0
                entry_price = 0

        elif position == -1:  # SHORT
            if price >= vama:
                pnl = (entry_price - price) * QTY
                realised_pnl += pnl
                capital += pnl
                print(f"🟣 SHORT EXIT @ {price:.2f} | REASON: Price >= VAMA | PnL={pnl:.2f}")
                position = 0
                entry_price = 0

    # ------------------------
    # SUMMARY
    # ------------------------
    if time.time() - last_summary >= SUMMARY_INTERVAL:
        equity = capital
        print("\n📘 SUMMARY:")
        print(f"Capital: {capital:.2f}")
        print(f"Realised PNL: {realised_pnl:.2f}")
        print("-----------------------------\n")
        last_summary = time.time()

    # ------------------------
    # DRAWDOWN STOP
    # ------------------------
    if capital <= START_CAPITAL * (1 - MAX_DRAWDOWN):
        print("\n🚨 STOP: Max drawdown reached.")
        break

    time.sleep(SLEEP)
